// frontend/src/editor/workspace/EditorTabBar.vue
<template>
  <header class="editor-tab-bar">
    <div class="editor-tab-bar__inner">
      <div class="editor-tab-bar__tabs-shell" @wheel.prevent="handleTabsWheel" @dragleave="handleTabsShellDragLeave">
        <div class="editor-tab-bar__tabs">
          <div
            v-for="tab in tabs"
            :key="tab.tabId"
            class="editor-tab-bar__tab-shell"
            :ref="(element) => setTabShellRef(tab.tabId, element)"
            :class="{
              'editor-tab-bar__tab-shell--active': tab.tabId === activeTabId,
              'editor-tab-bar__tab-shell--dragging': tab.tabId === draggedTabId,
              'editor-tab-bar__tab-shell--drop-before': tab.tabId === dropTargetTabId && dropPlacement === 'before',
              'editor-tab-bar__tab-shell--drop-after': tab.tabId === dropTargetTabId && dropPlacement === 'after',
            }"
            draggable="true"
            @auxclick="handleTabAuxClick(tab, $event)"
            @dragstart="handleTabDragStart(tab, $event)"
            @dragover.prevent="handleTabDragOver(tab, $event)"
            @drop.prevent="handleTabDrop(tab, $event)"
            @dragend="handleTabDragEnd"
          >
            <input
              v-if="editingTabId === tab.tabId"
              :ref="setTabNameInput"
              v-model="draftGraphName"
              class="editor-tab-bar__tab-name-input"
              :aria-label="`重命名 ${tab.title}`"
              @blur="commitGraphName"
              @keydown.enter.prevent="commitGraphName"
              @keydown.esc.prevent="cancelGraphNameEdit"
            />
            <button
              v-else
              type="button"
              class="editor-tab-bar__tab-activate"
              :title="buildEditorTabHint(tab, copy)"
              @click="$emit('activate-tab', tab.tabId)"
              @dblclick="startTabRename(tab)"
            >
              <span class="editor-tab-bar__tab-title">{{ tab.title }}</span>
            </button>
            <span class="editor-tab-bar__tab-status">
              <span v-if="tab.dirty" class="editor-tab-bar__dirty-dot" />
              <button
                type="button"
                class="editor-tab-bar__close"
                :class="{ 'editor-tab-bar__close--visible': tab.tabId === activeTabId }"
                aria-label="关闭标签页"
                @click.stop="$emit('close-tab', tab.tabId)"
              >
                ×
              </button>
            </span>
          </div>
        </div>
      </div>

      <div class="editor-tab-bar__controls">
        <button
          type="button"
          class="editor-tab-bar__state-pill"
          :class="{ 'editor-tab-bar__state-pill--active': isStatePanelOpen }"
          @click="$emit('toggle-state-panel')"
        >
          <span>{{ copy.state }}</span>
          <span class="editor-tab-bar__state-count">{{ activeStateCount }}</span>
        </button>

        <button type="button" class="editor-tab-bar__action" @click="$emit('create-new')">{{ copy.newGraph }}</button>

        <WorkspaceSelect
          v-model="selectedTemplateId"
          :options="templateOptions"
          :placeholder="selectPlaceholders.template"
          min-width-class-name="editor-tab-bar__select"
        />

        <WorkspaceSelect
          v-model="selectedGraphId"
          :options="graphOptions"
          :placeholder="selectPlaceholders.graph"
          min-width-class-name="editor-tab-bar__select editor-tab-bar__select--wide"
        />

        <button type="button" class="editor-tab-bar__action" @click="$emit('save-active-graph')">{{ copy.save }}</button>
        <button type="button" class="editor-tab-bar__action" @click="$emit('validate-active-graph')">{{ copy.validate }}</button>
        <button type="button" class="editor-tab-bar__action editor-tab-bar__action--primary" @click="$emit('run-active-graph')">
          {{ copy.run }}
        </button>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { computed, nextTick, ref, watch, type ComponentPublicInstance } from "vue";

import type { EditorWorkspaceTab } from "@/lib/editor-workspace";
import type { GraphDocument, TemplateRecord } from "@/types/node-system";
import WorkspaceSelect from "./WorkspaceSelect.vue";
import { buildWorkspaceSelectOptions } from "./workspaceSelectModel";
import {
  buildEditorTabHint,
  resolveEditorTabBarSelectPlaceholders,
  resolveEditorTabDropPlacement,
  ZH_EDITOR_TAB_BAR_COPY,
} from "./editorTabBarModel";

const props = defineProps<{
  tabs: EditorWorkspaceTab[];
  activeTabId: string | null;
  templates: TemplateRecord[];
  graphs: GraphDocument[];
  activeStateCount: number;
  isStatePanelOpen: boolean;
}>();

const emit = defineEmits<{
  (event: "activate-tab", tabId: string): void;
  (event: "close-tab", tabId: string): void;
  (event: "reorder-tab", sourceTabId: string, targetTabId: string, placement: "before" | "after"): void;
  (event: "create-new"): void;
  (event: "create-from-template", templateId: string): void;
  (event: "open-graph", graphId: string): void;
  (event: "rename-active-graph", name: string): void;
  (event: "toggle-state-panel"): void;
  (event: "save-active-graph"): void;
  (event: "validate-active-graph"): void;
  (event: "run-active-graph"): void;
}>();

const selectedTemplateId = ref("");
const selectedGraphId = ref("");
const editingTabId = ref<string | null>(null);
const draftGraphName = ref("");
const tabNameInput = ref<HTMLInputElement | null>(null);
const draggedTabId = ref<string | null>(null);
const dropTargetTabId = ref<string | null>(null);
const dropPlacement = ref<"before" | "after" | null>(null);
const revealTabId = ref<string | null>(null);
const copy = ZH_EDITOR_TAB_BAR_COPY;
const tabShellRefs = new Map<string, HTMLElement>();

const templateOptions = computed(() =>
  buildWorkspaceSelectOptions(
    props.templates.map((template) => ({
      value: template.template_id,
      label: template.label,
    })),
  ),
);

const graphOptions = computed(() =>
  buildWorkspaceSelectOptions(
    props.graphs.map((graph) => ({
      value: graph.graph_id,
      label: graph.name,
    })),
  ),
);

const selectPlaceholders = computed(() =>
  resolveEditorTabBarSelectPlaceholders({
    templateCount: templateOptions.value.length,
    graphCount: graphOptions.value.length,
    copy,
  }),
);

watch(selectedTemplateId, (nextValue) => {
  if (!nextValue) {
    return;
  }
  emit("create-from-template", nextValue);
  selectedTemplateId.value = "";
});

watch(selectedGraphId, (nextValue) => {
  if (!nextValue) {
    return;
  }
  emit("open-graph", nextValue);
  selectedGraphId.value = "";
});

watch(
  () => props.activeTabId,
  (nextTabId) => {
    if (!nextTabId || revealTabId.value) {
      return;
    }
    void scrollTabIntoView(nextTabId);
  },
);

watch(
  () => editingTabId.value,
  (nextTabId) => {
    if (!nextTabId) {
      return;
    }
    void scrollTabIntoView(nextTabId);
  },
);

watch(
  () => props.tabs.map((tab) => tab.tabId).join("|"),
  (nextSignature, previousSignature) => {
    if (!revealTabId.value || nextSignature === previousSignature) {
      return;
    }
    const nextRevealTabId = revealTabId.value;
    revealTabId.value = null;
    void scrollTabIntoView(nextRevealTabId);
  },
);

function setTabNameInput(element: Element | ComponentPublicInstance | null) {
  tabNameInput.value = element instanceof HTMLInputElement ? element : null;
}

function setTabShellRef(tabId: string, element: Element | ComponentPublicInstance | null) {
  if (element instanceof HTMLElement) {
    tabShellRefs.set(tabId, element);
    return;
  }

  tabShellRefs.delete(tabId);
}

async function scrollTabIntoView(tabId: string) {
  await nextTick();
  tabShellRefs.get(tabId)?.scrollIntoView({
    block: "nearest",
    inline: "center",
    behavior: "smooth",
  });
}

async function startTabRename(tab: EditorWorkspaceTab) {
  emit("activate-tab", tab.tabId);
  editingTabId.value = tab.tabId;
  draftGraphName.value = tab.title;
  await nextTick();
  tabNameInput.value?.focus();
  tabNameInput.value?.select();
}

function commitGraphName() {
  const editingTab = props.tabs.find((tab) => tab.tabId === editingTabId.value) ?? null;
  const nextName = draftGraphName.value.trim();
  if (editingTab && nextName && nextName !== editingTab.title) {
    emit("rename-active-graph", nextName);
  }
  editingTabId.value = null;
}

function cancelGraphNameEdit() {
  const editingTab = props.tabs.find((tab) => tab.tabId === editingTabId.value) ?? null;
  draftGraphName.value = editingTab?.title ?? "";
  editingTabId.value = null;
}

function handleTabAuxClick(tab: EditorWorkspaceTab, event: MouseEvent) {
  const target = event.target instanceof Element ? event.target : null;
  if (event.button !== 1 || target?.closest(".editor-tab-bar__close")) {
    return;
  }

  event.preventDefault();
  emit("close-tab", tab.tabId);
}

function handleTabDragStart(tab: EditorWorkspaceTab, event: DragEvent) {
  if (editingTabId.value === tab.tabId) {
    event.preventDefault();
    return;
  }

  draggedTabId.value = tab.tabId;
  dropTargetTabId.value = null;
  dropPlacement.value = null;
  event.dataTransfer?.setData("text/plain", tab.tabId);
  if (event.dataTransfer) {
    event.dataTransfer.effectAllowed = "move";
  }
}

function handleTabDragOver(tab: EditorWorkspaceTab, event: DragEvent) {
  if (!draggedTabId.value || draggedTabId.value === tab.tabId) {
    dropTargetTabId.value = null;
    dropPlacement.value = null;
    return;
  }

  const currentTarget = event.currentTarget;
  if (!(currentTarget instanceof HTMLElement)) {
    return;
  }

  const rect = currentTarget.getBoundingClientRect();
  dropTargetTabId.value = tab.tabId;
  dropPlacement.value = resolveEditorTabDropPlacement(event.clientX, rect.left, rect.width);
  if (event.dataTransfer) {
    event.dataTransfer.dropEffect = "move";
  }
}

function handleTabDrop(tab: EditorWorkspaceTab, event: DragEvent) {
  if (!draggedTabId.value || draggedTabId.value === tab.tabId) {
    handleTabDragEnd();
    return;
  }

  const currentTarget = event.currentTarget;
  if (!(currentTarget instanceof HTMLElement)) {
    handleTabDragEnd();
    return;
  }

  const rect = currentTarget.getBoundingClientRect();
  const placement = resolveEditorTabDropPlacement(event.clientX, rect.left, rect.width);
  revealTabId.value = draggedTabId.value;
  emit("reorder-tab", draggedTabId.value, tab.tabId, placement);
  handleTabDragEnd();
}

function handleTabDragEnd() {
  draggedTabId.value = null;
  dropTargetTabId.value = null;
  dropPlacement.value = null;
}

function handleTabsShellDragLeave(event: DragEvent) {
  const currentTarget = event.currentTarget;
  const relatedTarget = event.relatedTarget;
  if (!(currentTarget instanceof HTMLElement) || (relatedTarget instanceof Node && currentTarget.contains(relatedTarget))) {
    return;
  }

  dropTargetTabId.value = null;
  dropPlacement.value = null;
}

function handleTabsWheel(event: WheelEvent) {
  const currentTarget = event.currentTarget;
  if (!(currentTarget instanceof HTMLElement)) {
    return;
  }

  currentTarget.scrollLeft += Math.abs(event.deltaX) > Math.abs(event.deltaY) ? event.deltaX : event.deltaY;
}
</script>

<style scoped>
.editor-tab-bar {
  --editor-tab-rail-band-size: 4px;
  --editor-tab-body-height: 36px;
  --editor-tab-min-width: 168px;
  --editor-tab-max-width: 232px;
  position: relative;
  border-bottom: 1px solid rgba(154, 52, 18, 0.14);
  background:
    radial-gradient(circle at top left, rgba(191, 78, 39, 0.08), transparent 28%),
    linear-gradient(180deg, rgba(255, 250, 241, 0.98) 0%, rgba(248, 237, 219, 0.96) 100%);
  box-shadow:
    inset 0 1px 0 rgba(255, 255, 255, 0.6),
    0 10px 24px rgba(154, 52, 18, 0.08);
}

.editor-tab-bar::after {
  content: "";
  position: absolute;
  left: 0;
  right: 0;
  bottom: 0;
  height: 1px;
  background: rgba(154, 52, 18, 0.12);
}

.editor-tab-bar__inner {
  display: flex;
  min-width: 0;
  flex-wrap: nowrap;
  align-items: flex-end;
  gap: 14px;
  padding: 8px 16px 0;
}

.editor-tab-bar__tabs-shell {
  min-width: 0;
  flex: 1;
  overflow-x: auto;
  padding: var(--editor-tab-rail-band-size) 0;
  border-top: 1px solid rgba(132, 101, 72, 0.22);
  border-bottom: 1px solid rgba(78, 52, 30, 0.34);
  background: linear-gradient(180deg, rgba(122, 88, 58, 0.98) 0%, rgba(106, 74, 46, 0.98) 100%);
  box-shadow:
    inset 0 1px 0 rgba(255, 246, 230, 0.08),
    inset 0 -1px 0 rgba(61, 39, 20, 0.22);
  scrollbar-width: none;
}

.editor-tab-bar__tabs-shell::-webkit-scrollbar,
.editor-tab-bar__controls::-webkit-scrollbar {
  display: none;
}

.editor-tab-bar__tabs {
  display: flex;
  min-width: max-content;
  align-items: flex-end;
  gap: 0;
  padding: 0 12px 0 0;
  min-height: var(--editor-tab-body-height);
}

.editor-tab-bar__tab-shell {
  position: relative;
  isolation: isolate;
  box-sizing: border-box;
  flex: 0 0 auto;
  display: inline-flex;
  align-items: center;
  gap: 8px;
  min-width: var(--editor-tab-min-width);
  max-width: var(--editor-tab-max-width);
  height: var(--editor-tab-body-height);
  padding: 0 16px 0 18px;
  overflow: visible;
  border: none;
  border-radius: 0;
  background: transparent;
  color: rgba(255, 242, 226, 0.86);
  box-shadow: none;
  transition:
    background-color 160ms ease,
    border-color 160ms ease,
    box-shadow 160ms ease,
    color 160ms ease,
    transform 160ms ease;
}

.editor-tab-bar__tab-shell:not(.editor-tab-bar__tab-shell--active)::before {
  content: "";
  position: absolute;
  left: 0;
  top: 50%;
  width: 1px;
  height: 18px;
  background: rgba(154, 52, 18, 0.18);
  transform: translateY(-50%);
}

.editor-tab-bar__tab-shell:first-child:not(.editor-tab-bar__tab-shell--active)::before {
  content: none;
}

.editor-tab-bar__tab-shell:hover {
  color: rgba(37, 24, 14, 0.92);
}

.editor-tab-bar__tab-shell:not(.editor-tab-bar__tab-shell--active):hover {
  border-radius: 12px;
  background: linear-gradient(180deg, rgba(240, 225, 206, 0.88) 0%, rgba(228, 206, 180, 0.84) 100%);
  box-shadow:
    inset 0 1px 0 rgba(255, 250, 241, 0.56),
    0 2px 8px rgba(154, 52, 18, 0.05);
}

.editor-tab-bar__tab-shell:not(.editor-tab-bar__tab-shell--active):hover::before {
  opacity: 0;
}

.editor-tab-bar__tab-shell:hover + .editor-tab-bar__tab-shell::before {
  opacity: 0;
}

.editor-tab-bar__tab-shell--active + .editor-tab-bar__tab-shell::before {
  opacity: 0;
}

.editor-tab-bar__tab-shell--active {
  z-index: 2;
  height: var(--editor-tab-body-height);
  min-width: var(--editor-tab-min-width);
  margin: 0 8px 0 10px;
  padding: 0 16px 0 18px;
  border: 1px solid rgba(154, 52, 18, 0.18);
  border-bottom: none;
  border-radius: 14px 14px 0 0;
  background: linear-gradient(180deg, rgba(255, 252, 247, 1) 0%, rgba(248, 237, 219, 0.99) 100%);
  color: #2d1f12;
  box-shadow:
    inset 0 1px 0 rgba(255, 255, 255, 0.92),
    0 8px 18px rgba(154, 52, 18, 0.1);
}

.editor-tab-bar__tab-shell--active::before,
.editor-tab-bar__tab-shell--active::after {
  content: "";
  position: absolute;
  left: 0;
  right: 0;
  pointer-events: none;
}

.editor-tab-bar__tab-shell--active::before {
  z-index: -1;
  left: -1px;
  right: -1px;
  bottom: calc(-1 * var(--editor-tab-rail-band-size));
  height: var(--editor-tab-rail-band-size);
  background: rgba(248, 237, 219, 0.99);
}

.editor-tab-bar__tab-shell--active::after {
  left: -14px;
  right: -14px;
  bottom: calc(-1 * var(--editor-tab-rail-band-size));
  height: 12px;
  background:
    radial-gradient(circle at left top, transparent 10px, rgba(248, 237, 219, 0.99) 10.5px) left top / 14px 12px no-repeat,
    radial-gradient(circle at right top, transparent 10px, rgba(248, 237, 219, 0.99) 10.5px) right top / 14px 12px no-repeat;
  pointer-events: none;
}

.editor-tab-bar__tab-shell--active:hover {
  transform: none;
}

.editor-tab-bar__tab-shell--dragging {
  opacity: 0.78;
  transform: scale(0.98);
}

.editor-tab-bar__tab-shell--drop-before {
  box-shadow: inset 3px 0 0 rgba(191, 78, 39, 0.96);
}

.editor-tab-bar__tab-shell--drop-after {
  box-shadow: inset -3px 0 0 rgba(191, 78, 39, 0.96);
}

.editor-tab-bar__tab-activate {
  display: inline-flex;
  flex: 1;
  min-width: 0;
  position: relative;
  z-index: 1;
  align-items: center;
  border: none;
  background: transparent;
  padding: 0;
  color: inherit;
  text-align: left;
  cursor: pointer;
}

.editor-tab-bar__tab-name-input {
  min-width: 180px;
  width: 100%;
  position: relative;
  z-index: 1;
  border: 1px solid rgba(191, 78, 39, 0.28);
  border-radius: 12px;
  background: rgba(255, 252, 247, 0.98);
  padding: 5px 10px;
  color: inherit;
  font: inherit;
  outline: none;
  box-shadow: 0 0 0 3px rgba(191, 78, 39, 0.1);
}

.editor-tab-bar__tab-title {
  max-width: 100%;
  overflow: hidden;
  font-size: 0.9rem;
  font-weight: 450;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.editor-tab-bar__tab-shell--active .editor-tab-bar__tab-title {
  font-weight: 500;
}

.editor-tab-bar__tab-status {
  position: relative;
  z-index: 1;
  display: inline-flex;
  width: 22px;
  height: 22px;
  flex-shrink: 0;
}

.editor-tab-bar__dirty-dot {
  pointer-events: none;
  position: absolute;
  top: 50%;
  left: 50%;
  z-index: 1;
  width: 8px;
  height: 8px;
  border-radius: 999px;
  background: #c56b14;
  transform: translate(-50%, -50%);
  transition: opacity 150ms ease;
}

.editor-tab-bar__tab-shell:hover .editor-tab-bar__dirty-dot,
.editor-tab-bar__tab-shell--active .editor-tab-bar__dirty-dot {
  opacity: 0;
}

.editor-tab-bar__close {
  position: absolute;
  inset: 0;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border: none;
  border-radius: 999px;
  background: rgba(255, 252, 247, 0.22);
  color: rgba(88, 55, 30, 0.82);
  cursor: pointer;
  opacity: 0;
  transform: scale(0.92);
  transition: opacity 150ms ease, transform 150ms ease, background-color 150ms ease;
}

.editor-tab-bar__tab-shell:hover .editor-tab-bar__close,
.editor-tab-bar__close--visible {
  opacity: 1;
  transform: scale(1);
}

.editor-tab-bar__close:hover {
  background: rgba(154, 52, 18, 0.12);
}

.editor-tab-bar__controls {
  display: flex;
  min-width: 0;
  flex-wrap: nowrap;
  align-items: center;
  gap: 8px;
  overflow-x: auto;
  padding: 0 0 9px;
  scrollbar-width: none;
}

.editor-tab-bar__state-pill,
.editor-tab-bar__action {
  flex: 0 0 auto;
  min-height: 36px;
  border: 1px solid rgba(139, 120, 99, 0.18);
  border-radius: 14px;
  background: rgba(255, 255, 255, 0.82);
  padding: 8px 13px;
  color: #3c2914;
  box-shadow:
    inset 0 1px 0 rgba(255, 255, 255, 0.45),
    0 1px 0 rgba(255, 255, 255, 0.28);
}

.editor-tab-bar__state-pill {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  font-size: 0.92rem;
  font-weight: 500;
  cursor: pointer;
  transition: border-color 160ms ease, background-color 160ms ease, color 160ms ease;
}

.editor-tab-bar__state-pill:hover {
  background: white;
}

.editor-tab-bar__state-pill--active {
  border-color: rgba(217, 119, 6, 0.26);
  background: rgba(255, 244, 240, 0.94);
  color: rgba(154, 52, 18, 0.94);
}

.editor-tab-bar__state-count {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 24px;
  padding: 2px 8px;
  border: 1px solid rgba(154, 52, 18, 0.16);
  border-radius: 999px;
  background: rgba(255, 250, 241, 0.92);
  color: rgba(60, 41, 20, 0.72);
  font-size: 0.68rem;
}

.editor-tab-bar__select {
  min-width: 180px;
}

.editor-tab-bar__select--wide {
  min-width: 200px;
}

.editor-tab-bar__action {
  cursor: pointer;
  transition: border-color 160ms ease, background-color 160ms ease, color 160ms ease;
}

.editor-tab-bar__action:hover {
  background: white;
}

.editor-tab-bar__action--primary {
  border-color: rgba(154, 52, 18, 0.92);
  background: linear-gradient(180deg, rgba(191, 78, 39, 0.98) 0%, rgba(154, 52, 18, 0.98) 100%);
  color: rgba(255, 250, 241, 0.98);
  box-shadow: none;
}

.editor-tab-bar__action--primary:hover {
  background: linear-gradient(180deg, rgba(174, 65, 27, 0.98) 0%, rgba(141, 46, 14, 0.98) 100%);
}

@media (max-width: 1100px) {
  .editor-tab-bar__tab-name-input {
    min-width: 140px;
    width: 180px;
  }

  .editor-tab-bar__tab-shell {
    min-width: 146px;
    max-width: 190px;
  }
}
</style>

// frontend/components/editor/editor-tab-bar.tsx
"use client";

import {
  type KeyboardEvent as ReactKeyboardEvent,
  useEffect,
  useId,
  useRef,
  useState,
} from "react";

import { useLanguage } from "@/components/providers/language-provider";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/cn";
import type { EditorWorkspaceTab } from "@/lib/editor-workspace";
import type { CanonicalTemplateRecord } from "@/lib/node-system-canonical";
import type { GraphSummary } from "@/lib/types";

type EditorTabBarProps = {
  tabs: EditorWorkspaceTab[];
  activeTabId: string | null;
  templates: CanonicalTemplateRecord[];
  graphs: GraphSummary[];
  activeGraphName: string;
  activeStateCount: number;
  isStatePanelOpen: boolean;
  onActivateTab: (tabId: string) => void;
  onCloseTab: (tabId: string) => void;
  onCreateNew: () => void;
  onCreateFromTemplate: (templateId: string) => void;
  onOpenGraph: (graphId: string) => void;
  onRenameActiveGraph: (name: string) => void;
  onToggleStatePanel: () => void;
  onSaveActiveGraph: () => void;
  onValidateActiveGraph: () => void;
  onRunActiveGraph: () => void;
};

type WorkspaceSelectOption = {
  value: string;
  label: string;
};

const WORKSPACE_SELECT_CLASS =
  "min-h-[38px] w-full appearance-none rounded-[16px] border border-[rgba(154,52,18,0.14)] bg-[rgba(255,255,255,0.88)] px-3.5 py-2.5 pr-10 text-sm text-[var(--text)] shadow-[inset_0_1px_0_rgba(255,255,255,0.45)] outline-none transition focus:border-[rgba(154,52,18,0.28)] focus:bg-white";

function getTabBadge(tab: EditorWorkspaceTab) {
  switch (tab.kind) {
    case "template":
      return "template";
    case "existing":
      return "graph";
    case "new":
    default:
      return "draft";
  }
}

function WorkspaceSelect({
  value,
  placeholder,
  options,
  minWidthClassName,
  onValueChange,
}: {
  value: string;
  placeholder: string;
  options: WorkspaceSelectOption[];
  minWidthClassName: string;
  onValueChange: (value: string) => void;
}) {
  const listboxId = useId();
  const [open, setOpen] = useState(false);
  const [menuWidth, setMenuWidth] = useState<number | null>(null);
  const [activeIndex, setActiveIndex] = useState(-1);
  const triggerRef = useRef<HTMLButtonElement | null>(null);
  const menuRef = useRef<HTMLDivElement | null>(null);
  const optionRefs = useRef<Array<HTMLButtonElement | null>>([]);
  const selectedIndex = options.findIndex((option) => option.value === value);
  const selectedOption = options[selectedIndex] ?? null;
  const displayLabel = selectedOption?.label ?? placeholder;
  const isDisabled = options.length === 0;

  useEffect(() => {
    if (!open) {
      setActiveIndex(-1);
      return;
    }

    const syncMenuWidth = () => {
      const trigger = triggerRef.current;
      if (!trigger) return;
      setMenuWidth(Math.round(trigger.getBoundingClientRect().width));
    };

    syncMenuWidth();
    setActiveIndex(selectedIndex >= 0 ? selectedIndex : 0);

    const frameId = window.requestAnimationFrame(() => {
      menuRef.current?.focus();
    });

    const observer = typeof ResizeObserver !== "undefined" && triggerRef.current ? new ResizeObserver(syncMenuWidth) : null;
    if (observer && triggerRef.current) {
      observer.observe(triggerRef.current);
    } else {
      window.addEventListener("resize", syncMenuWidth);
    }

    const handlePointerDown = (event: PointerEvent) => {
      const target = event.target as Node | null;
      if (!target) return;
      if (triggerRef.current?.contains(target) || menuRef.current?.contains(target)) return;
      setOpen(false);
    };

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        setOpen(false);
      }
    };

    document.addEventListener("pointerdown", handlePointerDown);
    document.addEventListener("keydown", handleKeyDown);

    return () => {
      window.cancelAnimationFrame(frameId);
      observer?.disconnect();
      window.removeEventListener("resize", syncMenuWidth);
      document.removeEventListener("pointerdown", handlePointerDown);
      document.removeEventListener("keydown", handleKeyDown);
    };
  }, [open, selectedIndex]);

  useEffect(() => {
    if (!open || activeIndex < 0) return;
    optionRefs.current[activeIndex]?.scrollIntoView({ block: "nearest" });
  }, [activeIndex, open]);

  useEffect(() => {
    if (!isDisabled || !open) return;
    setOpen(false);
  }, [isDisabled, open]);

  const selectOption = (nextValue: string) => {
    onValueChange(nextValue);
    setOpen(false);
    window.requestAnimationFrame(() => {
      triggerRef.current?.focus();
    });
  };

  const moveActiveIndex = (direction: 1 | -1) => {
    if (options.length === 0) return;
    setActiveIndex((current) => {
      const baseIndex = current >= 0 ? current : selectedIndex >= 0 ? selectedIndex : 0;
      return (baseIndex + direction + options.length) % options.length;
    });
  };

  const handleTriggerKeyDown = (event: ReactKeyboardEvent<HTMLButtonElement>) => {
    if (isDisabled) return;

    if (event.key === "ArrowDown") {
      event.preventDefault();
      if (!open) {
        setOpen(true);
        return;
      }
      moveActiveIndex(1);
      return;
    }

    if (event.key === "ArrowUp") {
      event.preventDefault();
      if (!open) {
        setOpen(true);
        setActiveIndex(selectedIndex >= 0 ? selectedIndex : Math.max(options.length - 1, 0));
        return;
      }
      moveActiveIndex(-1);
      return;
    }

    if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      setOpen((current) => !current);
      return;
    }

    if (event.key === "Escape" && open) {
      event.preventDefault();
      setOpen(false);
    }
  };

  const handleMenuKeyDown = (event: ReactKeyboardEvent<HTMLDivElement>) => {
    if (event.key === "ArrowDown") {
      event.preventDefault();
      moveActiveIndex(1);
      return;
    }

    if (event.key === "ArrowUp") {
      event.preventDefault();
      moveActiveIndex(-1);
      return;
    }

    if (event.key === "Home") {
      event.preventDefault();
      setActiveIndex(0);
      return;
    }

    if (event.key === "End") {
      event.preventDefault();
      setActiveIndex(Math.max(options.length - 1, 0));
      return;
    }

    if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      if (activeIndex >= 0 && options[activeIndex]) {
        selectOption(options[activeIndex].value);
      }
      return;
    }

    if (event.key === "Tab") {
      setOpen(false);
    }
  };

  return (
    <div className={cn("relative", minWidthClassName)}>
      <button
        ref={triggerRef}
        type="button"
        aria-haspopup="listbox"
        aria-expanded={open}
        aria-controls={open ? listboxId : undefined}
        disabled={isDisabled}
        onKeyDown={handleTriggerKeyDown}
        onClick={() => {
          if (isDisabled) return;
          setOpen((current) => !current);
        }}
        className={cn(
          WORKSPACE_SELECT_CLASS,
          "flex items-center text-left",
          isDisabled ? "cursor-not-allowed opacity-60" : "cursor-pointer hover:border-[rgba(154,52,18,0.22)]",
        )}
      >
        <span className="block min-w-0 flex-1 truncate">{displayLabel}</span>
      </button>
      <svg
        viewBox="0 0 16 16"
        className={cn(
          "pointer-events-none absolute right-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 fill-none stroke-[var(--muted)] transition-transform",
          open ? "rotate-180" : null,
        )}
        strokeWidth="1.5"
      >
        <path d="m4.5 6 3.5 4 3.5-4" />
      </svg>
      {open ? (
        <div
          id={listboxId}
          ref={menuRef}
          role="listbox"
          aria-activedescendant={activeIndex >= 0 ? `${listboxId}-option-${activeIndex}` : undefined}
          tabIndex={-1}
          className="absolute left-0 top-[calc(100%+8px)] z-30 max-h-[260px] overflow-y-auto overflow-x-hidden rounded-[16px] border border-[rgba(154,52,18,0.16)] bg-[rgba(255,250,241,0.98)] p-1 shadow-[0_20px_40px_rgba(60,41,20,0.18)] backdrop-blur focus:outline-none"
          style={{ width: menuWidth ? `${menuWidth}px` : undefined }}
          onKeyDown={handleMenuKeyDown}
        >
          <div className="grid gap-1">
            {options.map((option, index) => {
              const selected = option.value === value;
              const active = index === activeIndex;
              return (
                <button
                  id={`${listboxId}-option-${index}`}
                  key={option.value}
                  ref={(node) => {
                    optionRefs.current[index] = node;
                  }}
                  type="button"
                  role="option"
                  aria-selected={selected}
                  className={cn(
                    "flex w-full items-center justify-between gap-3 rounded-[12px] px-3 py-2 text-left text-sm transition",
                    "text-[var(--text)] hover:bg-[rgba(154,52,18,0.08)]",
                    selected ? "bg-[rgba(154,52,18,0.12)] text-[var(--accent-strong)]" : active ? "bg-[rgba(154,52,18,0.06)]" : null,
                  )}
                  onMouseEnter={() => setActiveIndex(index)}
                  onClick={() => {
                    selectOption(option.value);
                  }}
                >
                  <span className="block min-w-0 flex-1 truncate">{option.label}</span>
                  <span className={cn("opacity-0 transition", selected ? "opacity-100" : null)}>
                    <svg viewBox="0 0 16 16" className="h-4 w-4 fill-none stroke-current" strokeWidth="1.8">
                      <path d="m3.5 8.5 3 3 6-7" />
                    </svg>
                  </span>
                </button>
              );
            })}
          </div>
        </div>
      ) : null}
    </div>
  );
}

export function EditorTabBar({
  tabs,
  activeTabId,
  templates,
  graphs,
  activeGraphName,
  activeStateCount,
  isStatePanelOpen,
  onActivateTab,
  onCloseTab,
  onCreateNew,
  onCreateFromTemplate,
  onOpenGraph,
  onRenameActiveGraph,
  onToggleStatePanel,
  onSaveActiveGraph,
  onValidateActiveGraph,
  onRunActiveGraph,
}: EditorTabBarProps) {
  const { language } = useLanguage();
  const [templateSelection, setTemplateSelection] = useState("");
  const [graphSelection, setGraphSelection] = useState("");
  const [isEditingGraphName, setIsEditingGraphName] = useState(false);
  const [draftGraphName, setDraftGraphName] = useState(activeGraphName);
  const copy =
    language === "zh"
      ? {
          newGraph: "新建图",
          fromTemplate: "从模板创建",
          openGraph: "打开已有图",
          noTemplates: "暂无模板",
          noGraphs: "暂无已保存图",
          dirty: "未保存",
          state: "State",
          save: "Save",
          validate: "Validate",
          run: "Run",
        }
      : {
          newGraph: "New Graph",
          fromTemplate: "From Template",
          openGraph: "Open Graph",
          noTemplates: "No templates",
          noGraphs: "No saved graphs",
          dirty: "Unsaved",
          state: "State",
          save: "Save",
          validate: "Validate",
          run: "Run",
        };

  const templateOptions = templates.map((template) => ({
    value: template.template_id,
    label: template.label,
  }));

  const graphOptions = graphs.map((graph) => ({
    value: graph.graph_id,
    label: graph.name,
  }));

  useEffect(() => {
    if (!isEditingGraphName) {
      setDraftGraphName(activeGraphName);
    }
  }, [activeGraphName, isEditingGraphName]);

  const commitGraphName = () => {
    const nextName = draftGraphName.trim();
    if (nextName && nextName !== activeGraphName) {
      onRenameActiveGraph(nextName);
    }
    setIsEditingGraphName(false);
  };

  return (
    <div className="border-b border-[rgba(154,52,18,0.14)] bg-[rgba(255,250,241,0.9)] px-4 py-2 shadow-[0_10px_24px_rgba(154,52,18,0.05)]">
      <div className="flex flex-wrap items-center gap-2">
        <div className="min-w-0 flex-1 overflow-x-auto">
          <div className="flex min-w-max items-center gap-1.5">
            {tabs.map((tab) => {
              const isActive = tab.tabId === activeTabId;
              const tabHint = [getTabBadge(tab), tab.dirty ? copy.dirty : null].filter(Boolean).join(" · ");
              return (
                <button
                  key={tab.tabId}
                  type="button"
                  title={tabHint}
                  onClick={() => onActivateTab(tab.tabId)}
                  className={cn(
                    "group inline-flex h-[36px] items-center gap-2 rounded-[14px] border px-3.5 text-left transition-all duration-150",
                    isActive
                      ? "border-[rgba(154,52,18,0.22)] bg-[rgba(255,255,255,0.94)] shadow-[0_8px_18px_rgba(154,52,18,0.08)]"
                      : "border-[rgba(154,52,18,0.1)] bg-[rgba(255,250,241,0.64)] hover:bg-[rgba(255,255,255,0.84)]",
                  )}
                >
                  <span className="min-w-0 truncate text-sm font-medium text-[var(--text)]">{tab.title}</span>
                  <span className="relative ml-0.5 h-5 w-5 shrink-0">
                    {tab.dirty ? (
                      <span className="pointer-events-none absolute left-1/2 top-1/2 z-10 h-2 w-2 -translate-x-1/2 -translate-y-1/2 rounded-full bg-[var(--accent-strong)] transition-opacity duration-150 group-hover:opacity-0" />
                    ) : null}
                    <span
                      role="button"
                      tabIndex={-1}
                      onClick={(event) => {
                        event.stopPropagation();
                        onCloseTab(tab.tabId);
                      }}
                      className={cn(
                        "absolute inset-0 inline-flex items-center justify-center rounded-full text-[var(--accent-strong)] transition-all duration-150 hover:bg-[rgba(154,52,18,0.08)]",
                        isActive ? "opacity-100" : "opacity-0 group-hover:opacity-100",
                      )}
                    >
                      ×
                    </span>
                  </span>
                </button>
              );
            })}
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {isEditingGraphName ? (
            <Input
              autoFocus
              className="h-[38px] min-w-[220px] rounded-[16px] border-[rgba(154,52,18,0.14)] bg-[rgba(255,255,255,0.88)] px-3.5 py-2.5 text-sm shadow-[inset_0_1px_0_rgba(255,255,255,0.45)]"
              value={draftGraphName}
              onChange={(event) => setDraftGraphName(event.target.value)}
              onBlur={commitGraphName}
              onKeyDown={(event) => {
                if (event.key === "Enter") {
                  event.preventDefault();
                  commitGraphName();
                }
                if (event.key === "Escape") {
                  event.preventDefault();
                  setDraftGraphName(activeGraphName);
                  setIsEditingGraphName(false);
                }
              }}
            />
          ) : (
            <button
              type="button"
              onDoubleClick={() => setIsEditingGraphName(true)}
              className="inline-flex h-[38px] min-w-[220px] items-center rounded-[16px] border border-[rgba(154,52,18,0.12)] bg-[rgba(255,255,255,0.72)] px-3.5 text-left text-sm font-medium text-[var(--text)] shadow-[inset_0_1px_0_rgba(255,255,255,0.38)] transition hover:border-[rgba(154,52,18,0.2)]"
              title={activeGraphName}
            >
              <span className="truncate">{activeGraphName}</span>
            </button>
          )}
          <button
            type="button"
            className={cn(
              "inline-flex h-[38px] items-center gap-2 rounded-[16px] border px-3.5 text-sm font-medium transition",
              isStatePanelOpen
                ? "border-[var(--accent)] bg-[rgba(255,244,240,0.94)] text-[var(--accent-strong)]"
                : "border-[rgba(154,52,18,0.14)] bg-[rgba(255,255,255,0.82)] text-[var(--text)] hover:bg-white",
            )}
            onClick={onToggleStatePanel}
          >
            <span>{copy.state}</span>
            <span className="rounded-full border border-[rgba(154,52,18,0.16)] bg-[rgba(255,250,241,0.92)] px-2 py-0.5 text-[0.68rem] text-[var(--muted)]">
              {activeStateCount}
            </span>
          </button>
          <Button size="sm" onClick={onCreateNew}>
            {copy.newGraph}
          </Button>
          <WorkspaceSelect
            value={templateSelection}
            placeholder={templateOptions.length === 0 ? copy.noTemplates : copy.fromTemplate}
            options={templateOptions}
            minWidthClassName="min-w-[180px]"
            onValueChange={(value) => {
              setTemplateSelection("");
              if (value) {
                onCreateFromTemplate(value);
              }
            }}
          />
          <WorkspaceSelect
            value={graphSelection}
            placeholder={graphOptions.length === 0 ? copy.noGraphs : copy.openGraph}
            options={graphOptions}
            minWidthClassName="min-w-[200px]"
            onValueChange={(value) => {
              setGraphSelection("");
              if (value) {
                onOpenGraph(value);
              }
            }}
          />
          <Button size="sm" onClick={onSaveActiveGraph}>
            {copy.save}
          </Button>
          <Button size="sm" onClick={onValidateActiveGraph}>
            {copy.validate}
          </Button>
          <Button size="sm" variant="primary" onClick={onRunActiveGraph}>
            {copy.run}
          </Button>
        </div>
      </div>
    </div>
  );
}
